# Generated by Django 4.2.11 on 2024-03-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XhsOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=100)),
                ('platform_orderId', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.platformcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('input_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_amount', models.PositiveIntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.platformcategory')),
            ],
        ),
    ]
