# Generated by Django 4.2.11 on 2024-03-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsource',
            name='postage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='邮费'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='uuid',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='随机字符串'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xhsorder',
            name='inaccount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='收益'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xhsorder',
            name='product_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xhs_orders', to='merchant.productsource', verbose_name='商品源'),
        ),
        migrations.AlterField(
            model_name='platformcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platformcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='平台名'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='input_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='min_amount',
            field=models.PositiveIntegerField(verbose_name='最低数量'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='output_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出价'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.platformcategory', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='title',
            field=models.CharField(max_length=255, verbose_name='商品标题'),
        ),
        migrations.AlterField(
            model_name='productsource',
            name='url',
            field=models.URLField(verbose_name='商品链接'),
        ),
        migrations.AlterField(
            model_name='xhsorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='xhsorder',
            name='orderId',
            field=models.CharField(max_length=100, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='xhsorder',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.platformcategory', verbose_name='第三方平台'),
        ),
        migrations.AlterField(
            model_name='xhsorder',
            name='platform_orderId',
            field=models.CharField(max_length=100, unique=True, verbose_name='第三方订单号'),
        ),
    ]
