# Generated by Django 4.2.11 on 2024-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_productsource_postage_productsource_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsource',
            name='url',
            field=models.CharField(max_length=255, verbose_name='商品链接'),
        ),
    ]
