# Generated by Django 4.2.11 on 2024-03-12 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_productsource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='xhsorder',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
