# Generated by Django 4.2.11 on 2024-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_xhsorder_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsource',
            name='uuid',
            field=models.CharField(max_length=32, unique=True, verbose_name='随机字符串'),
        ),
        migrations.AlterField(
            model_name='xhsorder',
            name='product_source',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='商品uid'),
            preserve_default=False,
        ),
    ]
