# Generated by Django 4.2.11 on 2024-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_alter_productsource_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xhsorder',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='购买数量'),
            preserve_default=False,
        ),
    ]
